name = "speedqueen-next"
main = ".open-next/worker.js"
compatibility_date = "2026-06-26"
compatibility_flags = [ "nodejs_compat" ]
assets = { directory = ".open-next/assets" }

[vars]
PROMO_START_DATE=2026-03-30T00:00:00+01:00
NEXT_PUBLIC_GOOGLE_PLACEID_ORLINSKIEGO=ChIJXw81dFBbFkcR37QA2sxXPU0
NEXT_PUBLIC_GOOGLE_PLACEID_PAWIA=ChIJ5zIcehhbFkcRg5JAJS7ICZo
NEXT_PUBLIC_GOOGLE_PLACEID_SLOWACKIEGO=ChIJLzFV3tFbFkcRri72hyj1PCI
RESEND_TO_EMAIL=kontakt@speedqueenkrk.pl
NEXT_PUBLIC_BASE_URL=https://speedqueen.netlify.app

[[r2_buckets]]
binding = "DISCOUNT_QR_CODES"
bucket_name = "discount-qr-codes"
