name = "speedqueen-next"
main = ".open-next/worker.js"
compatibility_date = "2026-06-26"
compatibility_flags = [ "nodejs_compat" ]
assets = { directory = ".open-next/assets" }

[[r2_buckets]]
binding = "DISCOUNT_QR_CODES"
bucket_name = "discount-qr-codes"
